language: ruby
sudo: false

before_install:
  - gem install bundler
  - gem update bundler

script: sh rake-script.sh

matrix:
  fast_finish: true
  include:
    - rvm: 2.0.0
    - rvm: 2.1.0
    - rvm: 2.1.1
    - rvm: 2.1.5
    - rvm: 2.2.0
    - rvm: 2.3.0
    - rvm: jruby-head
  allow_failures:
    - rvm: jruby-head

notifications:
  email:
    recipients:
      - dev-oneops@confiz.com
    on_success: always
    on_failure: always

addons:
  code_climate:
    repo_token: b1401494baa004d90402414cb33a7fc6420fd3693e60c677a120ddefd7d84cfd

jobs:
  include:
    - stage: gem release
      deploy:
        provider: script
        script: sh deploy.sh
        skip_cleanup: true
        on:
          tags: true
          branch: master
